### ISSUE TITLE
analyze page does not show data

### ISSUE THREAD

**Issue by mozartwalkingaround** [idealo/mongodb-slow-operations-profiler#23]
Hello,

After performing the installations, slow operations are written into the db and collection that I specified. However, when I press the analyze button, I cannot see any data.

Below you can find example of my config file, do you have any suggestions about it? I use mongo 4.4.18 version, and notablescan is 0 rightnow.

`{
    "collector": {
        "hosts": [
            "anotherlocal1:27017",
            "anotherlocal2:27017",
            "anotherlocal3:27017"
        ],
        "db": "dbopDB",
        "collection": "slowOps",
        "adminUser": "anusername",
        "adminPw": "apassword",
        "ssl": false
    },
    "profiled": [
        {
            "label": "Our Dev",
            "hosts": [
                "anotherlocal1:27017",
                "anotherlocal2:27017",
                "anotherlocal3:27017"
            ],
            "ns": [
                "*.*"
            ],
            "adminUser": "anusername",
            "adminPw": "apassword",
            "collect": false,
            "ssl": false,
            "slowMS": 100,
            "responseTimeoutInMs": 2000
        },
        {
            "label": "Our Prod",
            "hosts": [
                "somelocal1:27017",
                "somelocal2:27017",
                "somelocal3:27017"
            ],
            "ns": [
                "*.*"
            ],
            "adminUser": "******",
            "adminPw": "*******",
            "collect": false,
            "ssl": false,
            "slowMS": 100,
            "responseTimeoutInMs": 2000,
            "systemProfileCollectionMaxSizeInMB": 64
        }
    ],
    "yAxisScale": "milliseconds",
    "adminToken": "mySecureAdminToken",
    "defaultSlowMS": 100,
    "defaultResponseTimeoutInMs": 2000,
    "defaultExcludedDBs": [
        "admin",
        "local",
        "config"
    ],
    "maxWeblogEntries": 100,
    "systemProfileCollectionMaxSizeInMB": 16
}`

**Comment by kagahd** [comment]
Hello @mozartwalkingaround , according to your configuration (next time more reader friendly formatted please), your collector db seems to be the **same** db as the db to be profiled. You should avoid that because of recursion. 

Once you fixed that, start **first** the **profiling** and only **then** start **collecting**. If **no** slow operation had been profiled between the start of profiling and the start of collecting, the collector will sleep 1 hour before retrying to collect profiled slow operations. That's maybe the reason why you don't see slow operations on the analysis page within the first hour of the start of profiling & collecting.
In order to see slow opeartions on the analysis page, the profiled database/collection must have had some database operations that are slower than the `slowMs` threshold that you defined upon start of the profiler. Hence, you may lower `slowMs` threshold from 100 ms to only 1 ms or even 0 ms when you start the profiler. This increases the chances that some "slow" operations will be profiled that the collector can then collect instead to go sleep for 1 hour.

**Comment by mozartwalkingaround** [comment]
Hello @kagahd,

Thank you for your reply.

After uninstalling and reinstalling the app, all functions started working as they should. Also, I no longer profile the db at collectordb.
