### ISSUE TITLE
Does it give the full query or the truncated query

### ISSUE THREAD

**Issue by anmolarora** [idealo/mongodb-slow-operations-profiler#4]
Does this profiler give the full mongo query or the truncated query that you get from `currentOp` of mongo when query is very long?

**Comment by kagahd** [comment]
The profiler transforms the full mongo query into a **query shape**. For example a full query such as `field:{$elemMatch:{foo:1, bar:2, baz:{$gt:3}}}` will be shown as `field.$elemMatch{baz.$gt, foo, bar}`. So the concrete parameter **values** are omitted because they don't matter to analyze the query. However, operators such as $and, $or, $gt, $in etc. are included because they are important for the analysis.
